services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_development
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  web:
    build: .
    command: bash -c "chmod +x /rails/setup_credentials.sh && rails db:migrate && /rails/setup_credentials.sh && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/rails"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis