services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_app_development
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=your_development_secret_key_here
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - redis
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/app"
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=your_development_secret_key_here
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis